[package]
name = "tom_thread_pool"
version = "0.1.0"
edition = "2021"
description = "thread_pool"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
